version: '3.9'

services:
  fastapi_service:
    build:
      context: fastapi_app
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    networks:
      - app

  flask_frontend:
    build:
      context: flask_app
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - fastapi_service
    networks:
      - app

networks:
  app: